This is makeindex, version 2.15 [MiKTeX 2.9.6300 64-bit] (kpathsea + Thai support).
Scanning style file ./thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (462 entries accepted, 0 rejected).
Sorting entries......done (4493 comparisons).
Generating output file thesis.acr....done (215 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
