This is makeindex, version 2.15 [MiKTeX 2.9.6210 64-bit] (kpathsea + Thai support).
Scanning style file ./thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (9 comparisons).
Generating output file thesis.acr....done (6 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
